<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\ParrotInc.SquawkService.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\ParrotInc.SquawkService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
